[build-system]
requires = ["uv_build>=0.9.20,<0.10.0"]
build-backend = "uv_build"

[project]
version = "0.0.0"
name = "nevodchik"
requires-python = ">=3.14"
readme = "README.md"
classifiers = [
    "Private :: Do Not Upload"
]

[project.scripts]
nevodchik = "nevodchik.main:run"
